import type { DataTableColumn, ColumnDataType } from '@SMATCH-Digital-dev/vue-system-design'
import { JOB_STATUS_BADGE_DEFAULT_CLASS, JOB_STATUS_BADGE_STYLES } from '@/constants/jobStatus'
import { formatPlanningCreatedAtCell } from '@/composables/affecter/useAffecterData'

export function createJobsColumns(): DataTableColumn[] {
    return [
        {
            headerName: 'Référence',
            field: 'reference',
            sortable: true,
            dataType: 'text' as ColumnDataType,
            filterable: true,
            width: 200,
            editable: false,
            visible: true,
            draggable: true,
            autoSize: true,
            icon: 'mdi-file-document-outline',
            description: 'Référence du job',
        },
        {
            headerName: 'Statut',
            field: 'status',
            sortable: true,
            dataType: 'select' as ColumnDataType,
            filterable: true,
            width: 150,
            editable: false,
            visible: true,
            draggable: true,
            autoSize: true,
            icon: 'mdi-tag-outline',
            description: 'Statut du job',
            badgeStyles: JOB_STATUS_BADGE_STYLES,
            badgeDefaultClass: JOB_STATUS_BADGE_DEFAULT_CLASS,
        },
        {
            headerName: 'Emplacements',
            field: 'locations',
            sortable: false,
            dataType: 'text' as ColumnDataType,
            filterable: false,
            width: 200,
            editable: false,
            visible: true,
            draggable: true,
            autoSize: true,
            icon: 'mdi-map-marker-outline',
            description: 'Emplacements du job',
            nestedData: {
                key: 'locations',
                displayKey: 'location_reference',
                countSuffix: 'emplacements',
                expandable: true,
                showCount: true,
                title: 'Emplacements du job',
                columns: [
                    { field: 'reference', headerName: 'Référence', sortable: true, filterable: true, width: 150 },
                    { field: 'zone_name', headerName: 'Zone', sortable: true, filterable: true, width: 150 },
                    { field: 'sous_zone_name', headerName: 'Sous-zone', sortable: true, filterable: true, width: 150 },
                ],
            },
        },
        {
            headerName: 'Date création',
            field: 'created_at',
            sortable: true,
            dataType: 'date' as ColumnDataType,
            filterable: true,
            width: 150,
            editable: false,
            visible: true,
            draggable: true,
            autoSize: true,
            icon: 'mdi-calendar-outline',
            description: 'Date de création du job',
            dateFormat: 'fr-FR',
            dateOptions: {
                year: 'numeric' as const,
                month: '2-digit' as const,
                day: '2-digit' as const,
            },
            cellRenderer: formatPlanningCreatedAtCell as any,
        },
    ]
}

export function createLocationsColumns(): DataTableColumn[] {
    return [
        {
            headerName: 'ID',
            field: 'id',
            sortable: true,
            dataType: 'number' as ColumnDataType,
            filterable: true,
            width: 80,
            editable: false,
            visible: false,
            draggable: true,
            autoSize: true,
            description: 'Identifiant unique',
        },
        {
            headerName: 'Référence',
            field: 'reference',
            sortable: true,
            dataType: 'text' as ColumnDataType,
            filterable: true,
            width: 150,
            editable: false,
            visible: true,
            draggable: true,
            autoSize: true,
            icon: 'mdi-file-document-outline',
            description: 'Référence de la location',
        },
        {
            headerName: 'Réf. Location',
            field: 'location_reference',
            sortable: true,
            dataType: 'text' as ColumnDataType,
            filterable: true,
            width: 150,
            editable: false,
            visible: true,
            draggable: true,
            autoSize: true,
            icon: 'mdi-map-marker-outline',
            description: 'Référence de localisation',
        },
        {
            headerName: 'Zone',
            field: 'zone_name',
            sortable: true,
            dataType: 'text' as ColumnDataType,
            filterable: true,
            width: 150,
            editable: false,
            visible: true,
            draggable: true,
            autoSize: true,
            icon: 'mdi-layers-outline',
            description: 'Zone',
        },
        {
            headerName: 'Sous-zone',
            field: 'sous_zone_name',
            sortable: true,
            dataType: 'text' as ColumnDataType,
            filterable: true,
            width: 150,
            editable: false,
            visible: true,
            draggable: true,
            autoSize: true,
            icon: 'mdi-layers-outline',
            description: 'Sous-zone',
        },
    ]
}
